sudo: false
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION publishLocal
  - sbt sbt-scalajs-reflection/publishLocal
  - cd sbt-plugin-test
  - sbt ++$TRAVIS_SCALA_VERSION test
scala:
  - 2.10.6
  - 2.11.7
  - 2.12.0-M3
jdk:
  - oraclejdk8
